// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	LoginRequest
	LoginReply
	CreateUserRequest
	CreateUserReply
	GetUsersRequest
	GetUsersReply
	GetUserByIDRequest
	GetUserByIDReply
	UpdateUserRequest
	UpdateUserReply
	DeleteUserRequest
	DeleteUserReply
	ChangePasswordRequest
	ChangePasswordReply
	ResetPasswordRequest
	ResetPasswordReply
	GetMyselfRequest
	GetMyselfReply
	CreatePrivilegeProfileRequest
	CreatePrivilegeProfileReply
	GetPrivilegeProfilesRequest
	GetPrivilegeProfilesReply
	GetPrivilegeProfileByIDRequest
	GetPrivilegeProfileByIDReply
	UpdatePrivilegeProfileRequest
	UpdatePrivilegeProfileReply
	DeletePrivilegeProfileRequest
	DeletePrivilegeProfileReply
	GetLocationTreeRequest
	GetLocationTreeReply
	UpdateLocationTreeRequest
	UpdateLocationTreeReply
	GetScopeTreeRequest
	GetScopeTreeReply
	UpdateScopeTreeRequest
	UpdateScopeTreeReply
	ChangeVersionRequest
	ChangeVersionReply
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import creapptive_model "creapptive.com/ims-security/api/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Data  *creapptive_model.Myself `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginReply) GetData() *creapptive_model.Myself {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateUserRequest struct {
	User *creapptive_model.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateUserRequest) GetUser() *creapptive_model.User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserReply struct {
	Data  *creapptive_model.User `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CreateUserReply) Reset()                    { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string            { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()               {}
func (*CreateUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateUserReply) GetData() *creapptive_model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetUsersRequest struct {
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetUsersReply struct {
	Data  map[string]*creapptive_model.User `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error string                            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetUsersReply) Reset()                    { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string            { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()               {}
func (*GetUsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUsersReply) GetData() map[string]*creapptive_model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUsersReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetUserByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserByIDRequest) Reset()                    { *m = GetUserByIDRequest{} }
func (m *GetUserByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByIDRequest) ProtoMessage()               {}
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUserByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserByIDReply struct {
	Data  *creapptive_model.User `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetUserByIDReply) Reset()                    { *m = GetUserByIDReply{} }
func (m *GetUserByIDReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserByIDReply) ProtoMessage()               {}
func (*GetUserByIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetUserByIDReply) GetData() *creapptive_model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserByIDReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateUserRequest struct {
	User *creapptive_model.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateUserRequest) GetUser() *creapptive_model.User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserReply struct {
	Data  *creapptive_model.User `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UpdateUserReply) Reset()                    { *m = UpdateUserReply{} }
func (m *UpdateUserReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserReply) ProtoMessage()               {}
func (*UpdateUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateUserReply) GetData() *creapptive_model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserReply struct {
	Data  string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteUserReply) Reset()                    { *m = DeleteUserReply{} }
func (m *DeleteUserReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserReply) ProtoMessage()               {}
func (*DeleteUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteUserReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DeleteUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangePasswordRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=oldPassword" json:"oldPassword,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=newPassword" json:"newPassword,omitempty"`
}

func (m *ChangePasswordRequest) Reset()                    { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()               {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ChangePasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordReply struct {
	Data  string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ChangePasswordReply) Reset()                    { *m = ChangePasswordReply{} }
func (m *ChangePasswordReply) String() string            { return proto.CompactTextString(m) }
func (*ChangePasswordReply) ProtoMessage()               {}
func (*ChangePasswordReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ChangePasswordReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ChangePasswordReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResetPasswordRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ResetPasswordRequest) Reset()                    { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()               {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResetPasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResetPasswordReply struct {
	Data  string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ResetPasswordReply) Reset()                    { *m = ResetPasswordReply{} }
func (m *ResetPasswordReply) String() string            { return proto.CompactTextString(m) }
func (*ResetPasswordReply) ProtoMessage()               {}
func (*ResetPasswordReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ResetPasswordReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResetPasswordReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetMyselfRequest struct {
}

func (m *GetMyselfRequest) Reset()                    { *m = GetMyselfRequest{} }
func (m *GetMyselfRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMyselfRequest) ProtoMessage()               {}
func (*GetMyselfRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetMyselfReply struct {
	Data  *creapptive_model.Myself `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetMyselfReply) Reset()                    { *m = GetMyselfReply{} }
func (m *GetMyselfReply) String() string            { return proto.CompactTextString(m) }
func (*GetMyselfReply) ProtoMessage()               {}
func (*GetMyselfReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetMyselfReply) GetData() *creapptive_model.Myself {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetMyselfReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreatePrivilegeProfileRequest struct {
	PrivilegeProfile *creapptive_model.PrivilegeProfile `protobuf:"bytes,1,opt,name=privilegeProfile" json:"privilegeProfile,omitempty"`
}

func (m *CreatePrivilegeProfileRequest) Reset()                    { *m = CreatePrivilegeProfileRequest{} }
func (m *CreatePrivilegeProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePrivilegeProfileRequest) ProtoMessage()               {}
func (*CreatePrivilegeProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreatePrivilegeProfileRequest) GetPrivilegeProfile() *creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.PrivilegeProfile
	}
	return nil
}

type CreatePrivilegeProfileReply struct {
	Data  *creapptive_model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                             `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CreatePrivilegeProfileReply) Reset()                    { *m = CreatePrivilegeProfileReply{} }
func (m *CreatePrivilegeProfileReply) String() string            { return proto.CompactTextString(m) }
func (*CreatePrivilegeProfileReply) ProtoMessage()               {}
func (*CreatePrivilegeProfileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CreatePrivilegeProfileReply) GetData() *creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreatePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPrivilegeProfilesRequest struct {
}

func (m *GetPrivilegeProfilesRequest) Reset()                    { *m = GetPrivilegeProfilesRequest{} }
func (m *GetPrivilegeProfilesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPrivilegeProfilesRequest) ProtoMessage()               {}
func (*GetPrivilegeProfilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type GetPrivilegeProfilesReply struct {
	Data  map[string]*creapptive_model.PrivilegeProfile `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error string                                        `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetPrivilegeProfilesReply) Reset()                    { *m = GetPrivilegeProfilesReply{} }
func (m *GetPrivilegeProfilesReply) String() string            { return proto.CompactTextString(m) }
func (*GetPrivilegeProfilesReply) ProtoMessage()               {}
func (*GetPrivilegeProfilesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetPrivilegeProfilesReply) GetData() map[string]*creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPrivilegeProfilesReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPrivilegeProfileByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetPrivilegeProfileByIDRequest) Reset()         { *m = GetPrivilegeProfileByIDRequest{} }
func (m *GetPrivilegeProfileByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrivilegeProfileByIDRequest) ProtoMessage()    {}
func (*GetPrivilegeProfileByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *GetPrivilegeProfileByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPrivilegeProfileByIDReply struct {
	Data  *creapptive_model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                             `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetPrivilegeProfileByIDReply) Reset()                    { *m = GetPrivilegeProfileByIDReply{} }
func (m *GetPrivilegeProfileByIDReply) String() string            { return proto.CompactTextString(m) }
func (*GetPrivilegeProfileByIDReply) ProtoMessage()               {}
func (*GetPrivilegeProfileByIDReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetPrivilegeProfileByIDReply) GetData() *creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPrivilegeProfileByIDReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdatePrivilegeProfileRequest struct {
	PrivilegeProfile *creapptive_model.PrivilegeProfile `protobuf:"bytes,1,opt,name=privilegeProfile" json:"privilegeProfile,omitempty"`
}

func (m *UpdatePrivilegeProfileRequest) Reset()                    { *m = UpdatePrivilegeProfileRequest{} }
func (m *UpdatePrivilegeProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePrivilegeProfileRequest) ProtoMessage()               {}
func (*UpdatePrivilegeProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *UpdatePrivilegeProfileRequest) GetPrivilegeProfile() *creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.PrivilegeProfile
	}
	return nil
}

type UpdatePrivilegeProfileReply struct {
	Data  *creapptive_model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                             `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UpdatePrivilegeProfileReply) Reset()                    { *m = UpdatePrivilegeProfileReply{} }
func (m *UpdatePrivilegeProfileReply) String() string            { return proto.CompactTextString(m) }
func (*UpdatePrivilegeProfileReply) ProtoMessage()               {}
func (*UpdatePrivilegeProfileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *UpdatePrivilegeProfileReply) GetData() *creapptive_model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdatePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeletePrivilegeProfileRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePrivilegeProfileRequest) Reset()                    { *m = DeletePrivilegeProfileRequest{} }
func (m *DeletePrivilegeProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePrivilegeProfileRequest) ProtoMessage()               {}
func (*DeletePrivilegeProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *DeletePrivilegeProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePrivilegeProfileReply struct {
	Data  string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *DeletePrivilegeProfileReply) Reset()                    { *m = DeletePrivilegeProfileReply{} }
func (m *DeletePrivilegeProfileReply) String() string            { return proto.CompactTextString(m) }
func (*DeletePrivilegeProfileReply) ProtoMessage()               {}
func (*DeletePrivilegeProfileReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *DeletePrivilegeProfileReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DeletePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetLocationTreeRequest struct {
}

func (m *GetLocationTreeRequest) Reset()                    { *m = GetLocationTreeRequest{} }
func (m *GetLocationTreeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLocationTreeRequest) ProtoMessage()               {}
func (*GetLocationTreeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type GetLocationTreeReply struct {
	Data  []*creapptive_model.LocationNode `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Error string                           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetLocationTreeReply) Reset()                    { *m = GetLocationTreeReply{} }
func (m *GetLocationTreeReply) String() string            { return proto.CompactTextString(m) }
func (*GetLocationTreeReply) ProtoMessage()               {}
func (*GetLocationTreeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetLocationTreeReply) GetData() []*creapptive_model.LocationNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetLocationTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateLocationTreeRequest struct {
	Locations []*creapptive_model.LocationNode `protobuf:"bytes,1,rep,name=locations" json:"locations,omitempty"`
}

func (m *UpdateLocationTreeRequest) Reset()                    { *m = UpdateLocationTreeRequest{} }
func (m *UpdateLocationTreeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateLocationTreeRequest) ProtoMessage()               {}
func (*UpdateLocationTreeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *UpdateLocationTreeRequest) GetLocations() []*creapptive_model.LocationNode {
	if m != nil {
		return m.Locations
	}
	return nil
}

type UpdateLocationTreeReply struct {
	Data  []*creapptive_model.LocationNode `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Error string                           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UpdateLocationTreeReply) Reset()                    { *m = UpdateLocationTreeReply{} }
func (m *UpdateLocationTreeReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateLocationTreeReply) ProtoMessage()               {}
func (*UpdateLocationTreeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *UpdateLocationTreeReply) GetData() []*creapptive_model.LocationNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateLocationTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetScopeTreeRequest struct {
}

func (m *GetScopeTreeRequest) Reset()                    { *m = GetScopeTreeRequest{} }
func (m *GetScopeTreeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetScopeTreeRequest) ProtoMessage()               {}
func (*GetScopeTreeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type GetScopeTreeReply struct {
	Data  []*creapptive_model.ScopeNode `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Error string                        `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetScopeTreeReply) Reset()                    { *m = GetScopeTreeReply{} }
func (m *GetScopeTreeReply) String() string            { return proto.CompactTextString(m) }
func (*GetScopeTreeReply) ProtoMessage()               {}
func (*GetScopeTreeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *GetScopeTreeReply) GetData() []*creapptive_model.ScopeNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetScopeTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateScopeTreeRequest struct {
	Scopes []*creapptive_model.ScopeNode `protobuf:"bytes,1,rep,name=scopes" json:"scopes,omitempty"`
}

func (m *UpdateScopeTreeRequest) Reset()                    { *m = UpdateScopeTreeRequest{} }
func (m *UpdateScopeTreeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateScopeTreeRequest) ProtoMessage()               {}
func (*UpdateScopeTreeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *UpdateScopeTreeRequest) GetScopes() []*creapptive_model.ScopeNode {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type UpdateScopeTreeReply struct {
	Data  []*creapptive_model.ScopeNode `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Error string                        `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UpdateScopeTreeReply) Reset()                    { *m = UpdateScopeTreeReply{} }
func (m *UpdateScopeTreeReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateScopeTreeReply) ProtoMessage()               {}
func (*UpdateScopeTreeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *UpdateScopeTreeReply) GetData() []*creapptive_model.ScopeNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateScopeTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangeVersionRequest struct {
}

func (m *ChangeVersionRequest) Reset()                    { *m = ChangeVersionRequest{} }
func (m *ChangeVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeVersionRequest) ProtoMessage()               {}
func (*ChangeVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type ChangeVersionReply struct {
	Data  *creapptive_model.ChangeVersion `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Error string                          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ChangeVersionReply) Reset()                    { *m = ChangeVersionReply{} }
func (m *ChangeVersionReply) String() string            { return proto.CompactTextString(m) }
func (*ChangeVersionReply) ProtoMessage()               {}
func (*ChangeVersionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *ChangeVersionReply) GetData() *creapptive_model.ChangeVersion {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChangeVersionReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "creapptive.message.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "creapptive.message.LoginReply")
	proto.RegisterType((*CreateUserRequest)(nil), "creapptive.message.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "creapptive.message.CreateUserReply")
	proto.RegisterType((*GetUsersRequest)(nil), "creapptive.message.GetUsersRequest")
	proto.RegisterType((*GetUsersReply)(nil), "creapptive.message.GetUsersReply")
	proto.RegisterType((*GetUserByIDRequest)(nil), "creapptive.message.GetUserByIDRequest")
	proto.RegisterType((*GetUserByIDReply)(nil), "creapptive.message.GetUserByIDReply")
	proto.RegisterType((*UpdateUserRequest)(nil), "creapptive.message.UpdateUserRequest")
	proto.RegisterType((*UpdateUserReply)(nil), "creapptive.message.UpdateUserReply")
	proto.RegisterType((*DeleteUserRequest)(nil), "creapptive.message.DeleteUserRequest")
	proto.RegisterType((*DeleteUserReply)(nil), "creapptive.message.DeleteUserReply")
	proto.RegisterType((*ChangePasswordRequest)(nil), "creapptive.message.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordReply)(nil), "creapptive.message.ChangePasswordReply")
	proto.RegisterType((*ResetPasswordRequest)(nil), "creapptive.message.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordReply)(nil), "creapptive.message.ResetPasswordReply")
	proto.RegisterType((*GetMyselfRequest)(nil), "creapptive.message.GetMyselfRequest")
	proto.RegisterType((*GetMyselfReply)(nil), "creapptive.message.GetMyselfReply")
	proto.RegisterType((*CreatePrivilegeProfileRequest)(nil), "creapptive.message.CreatePrivilegeProfileRequest")
	proto.RegisterType((*CreatePrivilegeProfileReply)(nil), "creapptive.message.CreatePrivilegeProfileReply")
	proto.RegisterType((*GetPrivilegeProfilesRequest)(nil), "creapptive.message.GetPrivilegeProfilesRequest")
	proto.RegisterType((*GetPrivilegeProfilesReply)(nil), "creapptive.message.GetPrivilegeProfilesReply")
	proto.RegisterType((*GetPrivilegeProfileByIDRequest)(nil), "creapptive.message.GetPrivilegeProfileByIDRequest")
	proto.RegisterType((*GetPrivilegeProfileByIDReply)(nil), "creapptive.message.GetPrivilegeProfileByIDReply")
	proto.RegisterType((*UpdatePrivilegeProfileRequest)(nil), "creapptive.message.UpdatePrivilegeProfileRequest")
	proto.RegisterType((*UpdatePrivilegeProfileReply)(nil), "creapptive.message.UpdatePrivilegeProfileReply")
	proto.RegisterType((*DeletePrivilegeProfileRequest)(nil), "creapptive.message.DeletePrivilegeProfileRequest")
	proto.RegisterType((*DeletePrivilegeProfileReply)(nil), "creapptive.message.DeletePrivilegeProfileReply")
	proto.RegisterType((*GetLocationTreeRequest)(nil), "creapptive.message.GetLocationTreeRequest")
	proto.RegisterType((*GetLocationTreeReply)(nil), "creapptive.message.GetLocationTreeReply")
	proto.RegisterType((*UpdateLocationTreeRequest)(nil), "creapptive.message.UpdateLocationTreeRequest")
	proto.RegisterType((*UpdateLocationTreeReply)(nil), "creapptive.message.UpdateLocationTreeReply")
	proto.RegisterType((*GetScopeTreeRequest)(nil), "creapptive.message.GetScopeTreeRequest")
	proto.RegisterType((*GetScopeTreeReply)(nil), "creapptive.message.GetScopeTreeReply")
	proto.RegisterType((*UpdateScopeTreeRequest)(nil), "creapptive.message.UpdateScopeTreeRequest")
	proto.RegisterType((*UpdateScopeTreeReply)(nil), "creapptive.message.UpdateScopeTreeReply")
	proto.RegisterType((*ChangeVersionRequest)(nil), "creapptive.message.ChangeVersionRequest")
	proto.RegisterType((*ChangeVersionReply)(nil), "creapptive.message.ChangeVersionReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x7f, 0x4f, 0x13, 0x41,
	0x10, 0x4d, 0xcb, 0x8f, 0xd8, 0xa9, 0xfc, 0xe8, 0x52, 0x6a, 0xa1, 0x16, 0xc9, 0x6a, 0x14, 0x11,
	0x5b, 0x03, 0x89, 0x12, 0x35, 0x36, 0x01, 0xb4, 0x31, 0x02, 0x36, 0x05, 0x4c, 0xc4, 0x18, 0x3d,
	0x7b, 0x43, 0xbd, 0x70, 0xed, 0x9e, 0xbb, 0x57, 0x48, 0x3f, 0x99, 0x1f, 0xc6, 0x2f, 0x63, 0xf6,
	0x6e, 0x5b, 0xee, 0x47, 0xef, 0x28, 0xf1, 0xe2, 0x7f, 0xbd, 0x99, 0x37, 0xf3, 0xde, 0xcc, 0xde,
	0xbe, 0x1e, 0xcc, 0x74, 0x50, 0x08, 0xad, 0x8d, 0x15, 0x8b, 0x33, 0x9b, 0x11, 0xd2, 0xe2, 0xa8,
	0x59, 0x96, 0x6d, 0x5c, 0x60, 0x45, 0x65, 0x96, 0xb3, 0x1d, 0xa6, 0xa3, 0xe9, 0x02, 0xe8, 0x3b,
	0xb8, 0xbd, 0xcf, 0xda, 0x46, 0xb7, 0x89, 0xbf, 0x7a, 0x28, 0x6c, 0xb2, 0x0c, 0xb7, 0x7a, 0x02,
	0x79, 0x57, 0xeb, 0x60, 0x31, 0xb5, 0x9a, 0x5a, 0xcb, 0x34, 0x87, 0xcf, 0x32, 0x67, 0x69, 0x42,
	0x5c, 0x32, 0xae, 0x17, 0xd3, 0x6e, 0x6e, 0xf0, 0x4c, 0x1b, 0x00, 0xaa, 0x8f, 0x65, 0xf6, 0xc9,
	0x06, 0x4c, 0xea, 0x9a, 0xad, 0x39, 0x1d, 0xb2, 0x9b, 0xc5, 0x8a, 0x57, 0x85, 0x43, 0x7e, 0xd0,
	0x17, 0x68, 0x9e, 0x35, 0x1d, 0x14, 0xc9, 0xc3, 0x14, 0x72, 0xce, 0xb8, 0x6a, 0xea, 0x3e, 0xd0,
	0x1a, 0xe4, 0x76, 0x39, 0x6a, 0x36, 0x9e, 0x08, 0xe4, 0x03, 0x79, 0xeb, 0x30, 0x29, 0xe5, 0xa8,
	0xc6, 0x85, 0x70, 0x63, 0x07, 0xec, 0x60, 0xe8, 0x11, 0xcc, 0x79, 0x1b, 0x48, 0x5d, 0xeb, 0x3e,
	0x5d, 0x91, 0xe5, 0x31, 0xaa, 0x72, 0x30, 0x57, 0x47, 0x5b, 0xc2, 0x84, 0xd2, 0x44, 0x7f, 0xa7,
	0x60, 0xe6, 0x2a, 0x26, 0x69, 0x6a, 0x43, 0x9a, 0x89, 0xb5, 0xec, 0xe6, 0x93, 0x4a, 0xf8, 0x10,
	0x2a, 0xbe, 0x82, 0xca, 0x9e, 0x66, 0x6b, 0x6f, 0xbb, 0x36, 0xef, 0xc7, 0x71, 0x2f, 0x7f, 0x84,
	0xcc, 0x10, 0x48, 0xe6, 0x61, 0xe2, 0x1c, 0xfb, 0xea, 0x8c, 0xe4, 0x4f, 0xb2, 0x01, 0x53, 0x17,
	0x9a, 0xd9, 0x43, 0xa7, 0x28, 0x7a, 0x3a, 0x17, 0xf4, 0x32, 0xbd, 0x9d, 0xa2, 0x0f, 0x80, 0x28,
	0x1d, 0x3b, 0xfd, 0xf7, 0x7b, 0x83, 0x1d, 0xcf, 0x42, 0xda, 0xd0, 0x55, 0xe3, 0xb4, 0xa1, 0xd3,
	0x63, 0x98, 0xf7, 0xa1, 0x92, 0x59, 0x64, 0x0d, 0x72, 0x27, 0x96, 0xfe, 0x6f, 0xc7, 0xeb, 0x6d,
	0x90, 0x8c, 0xaa, 0xfb, 0x90, 0xdb, 0x43, 0x13, 0xfd, 0xaa, 0x82, 0x0b, 0x79, 0x05, 0x73, 0x5e,
	0x90, 0x64, 0x26, 0x1e, 0xe6, 0x4c, 0x2c, 0xc3, 0x39, 0x2c, 0xee, 0xfe, 0xd4, 0xba, 0x6d, 0x6c,
	0xa8, 0xab, 0x13, 0xc1, 0x42, 0x56, 0x21, 0xcb, 0x4c, 0xbd, 0xe1, 0xbf, 0x70, 0xde, 0x90, 0x44,
	0x74, 0xf1, 0x72, 0x88, 0x98, 0x70, 0x11, 0x9e, 0x10, 0xad, 0xc1, 0x42, 0x90, 0xec, 0x66, 0x6a,
	0x1f, 0x42, 0xbe, 0x89, 0x02, 0xed, 0x6b, 0xc4, 0xd2, 0x37, 0x40, 0x02, 0xb8, 0x9b, 0xf1, 0x10,
	0xe7, 0x1d, 0x53, 0xae, 0xa0, 0xee, 0xd5, 0x31, 0xcc, 0x7a, 0x62, 0x49, 0xd9, 0x0a, 0x83, 0xb2,
	0xeb, 0x0a, 0x0d, 0x6e, 0x5c, 0x18, 0x26, 0xb6, 0xb1, 0xc1, 0xd9, 0x99, 0x61, 0xe2, 0x60, 0xb4,
	0x43, 0x98, 0xb7, 0x02, 0x29, 0x45, 0x48, 0xc3, 0x84, 0xa1, 0x26, 0xa1, 0x5a, 0x7a, 0x0e, 0xa5,
	0x28, 0x42, 0x39, 0xd3, 0x73, 0xdf, 0x4c, 0xe3, 0x50, 0xc4, 0x4d, 0x57, 0x86, 0x52, 0x1d, 0xed,
	0x60, 0xc9, 0xd0, 0xaa, 0xfe, 0xa4, 0x60, 0x69, 0x74, 0x5e, 0x4a, 0xf9, 0xe0, 0xb3, 0xad, 0x17,
	0x11, 0xb6, 0x35, 0xba, 0x78, 0x4c, 0x0b, 0xfb, 0x12, 0x6f, 0x61, 0xdb, 0x7e, 0x0b, 0x1b, 0x67,
	0x1b, 0x1e, 0x3b, 0x7b, 0x06, 0x2b, 0x23, 0xf4, 0xc5, 0x59, 0x9b, 0x09, 0x77, 0x23, 0x2b, 0x92,
	0x3f, 0x1c, 0x06, 0x65, 0xd7, 0xb1, 0xfe, 0xe3, 0xab, 0x17, 0x45, 0x98, 0xfc, 0x74, 0x55, 0x28,
	0xbb, 0xae, 0x18, 0x35, 0x5d, 0x70, 0xf9, 0x75, 0x28, 0x45, 0x15, 0xdc, 0xcc, 0x3c, 0x8a, 0x50,
	0xa8, 0xa3, 0xbd, 0xcf, 0x5a, 0x9a, 0x6d, 0xb0, 0xee, 0x31, 0xc7, 0x01, 0x25, 0xfd, 0x0e, 0xf9,
	0x50, 0x46, 0xf6, 0xde, 0xf4, 0xbd, 0xe9, 0x2b, 0xe1, 0xc9, 0x07, 0x25, 0x87, 0x4c, 0x8f, 0x9f,
	0xfa, 0x33, 0x2c, 0xb9, 0x2b, 0x1e, 0x41, 0x4f, 0x5e, 0x43, 0xc6, 0x54, 0x61, 0x31, 0x26, 0xd7,
	0x55, 0x01, 0x6d, 0xc1, 0x9d, 0x51, 0xad, 0x93, 0xd5, 0xbf, 0x08, 0x0b, 0x75, 0xb4, 0x8f, 0x5a,
	0xcc, 0x42, 0xef, 0xe2, 0x4e, 0x21, 0xe7, 0x0f, 0x4b, 0xd6, 0xaa, 0x8f, 0xb5, 0x14, 0x66, 0x75,
	0xf0, 0xd7, 0x52, 0x1e, 0x40, 0xc1, 0x9d, 0x2b, 0xc8, 0x4a, 0xb6, 0x60, 0x5a, 0xc8, 0x98, 0x18,
	0x87, 0x42, 0x41, 0xe9, 0x57, 0xc8, 0x87, 0xda, 0x25, 0xa8, 0xb6, 0x00, 0x79, 0xf7, 0x2f, 0xf4,
	0x13, 0x72, 0x61, 0xb0, 0xc1, 0x87, 0x32, 0xfd, 0x06, 0x24, 0x10, 0x97, 0xa4, 0x5b, 0xbe, 0x2b,
	0x75, 0x2f, 0x4c, 0xea, 0xaf, 0x89, 0x21, 0xde, 0x79, 0x7c, 0xfa, 0xc8, 0x53, 0xdd, 0x62, 0x9d,
	0xaa, 0xd1, 0x11, 0x4f, 0x05, 0xb6, 0x7a, 0xdc, 0xb0, 0xfb, 0x55, 0xcd, 0x32, 0xaa, 0xca, 0x95,
	0x7f, 0x4c, 0x3b, 0xdf, 0xf2, 0x5b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x34, 0x78, 0x71, 0x84,
	0xfd, 0x0b, 0x00, 0x00,
}
