// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	model "creapptive.com/ims-security/api/model"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Data                 *model.Myself `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetData() *model.Myself {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateUserRequest struct {
	User                 *model.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *model.User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserReply struct {
	Data                 *model.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetData() *model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUsersReply struct {
	Data                 map[string]*model.User `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetUsersReply) Reset()         { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()    {}
func (*GetUsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *GetUsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReply.Unmarshal(m, b)
}
func (m *GetUsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReply.Marshal(b, m, deterministic)
}
func (m *GetUsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReply.Merge(m, src)
}
func (m *GetUsersReply) XXX_Size() int {
	return xxx_messageInfo_GetUsersReply.Size(m)
}
func (m *GetUsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReply proto.InternalMessageInfo

func (m *GetUsersReply) GetData() map[string]*model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUsersReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetUserByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIDRequest) Reset()         { *m = GetUserByIDRequest{} }
func (m *GetUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDRequest) ProtoMessage()    {}
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *GetUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDRequest.Unmarshal(m, b)
}
func (m *GetUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDRequest.Merge(m, src)
}
func (m *GetUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDRequest.Size(m)
}
func (m *GetUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDRequest proto.InternalMessageInfo

func (m *GetUserByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserByIDReply struct {
	Data                 *model.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserByIDReply) Reset()         { *m = GetUserByIDReply{} }
func (m *GetUserByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDReply) ProtoMessage()    {}
func (*GetUserByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *GetUserByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDReply.Unmarshal(m, b)
}
func (m *GetUserByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDReply.Marshal(b, m, deterministic)
}
func (m *GetUserByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDReply.Merge(m, src)
}
func (m *GetUserByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDReply.Size(m)
}
func (m *GetUserByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDReply proto.InternalMessageInfo

func (m *GetUserByIDReply) GetData() *model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserByIDReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateUserRequest struct {
	User                 *model.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *model.User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserReply struct {
	Data                 *model.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateUserReply) Reset()         { *m = UpdateUserReply{} }
func (m *UpdateUserReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReply) ProtoMessage()    {}
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *UpdateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReply.Unmarshal(m, b)
}
func (m *UpdateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReply.Marshal(b, m, deterministic)
}
func (m *UpdateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReply.Merge(m, src)
}
func (m *UpdateUserReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReply.Size(m)
}
func (m *UpdateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReply proto.InternalMessageInfo

func (m *UpdateUserReply) GetData() *model.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReply) Reset()         { *m = DeleteUserReply{} }
func (m *DeleteUserReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReply) ProtoMessage()    {}
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *DeleteUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReply.Unmarshal(m, b)
}
func (m *DeleteUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReply.Marshal(b, m, deterministic)
}
func (m *DeleteUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReply.Merge(m, src)
}
func (m *DeleteUserReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReply.Size(m)
}
func (m *DeleteUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReply proto.InternalMessageInfo

func (m *DeleteUserReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DeleteUserReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangePasswordRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReply) Reset()         { *m = ChangePasswordReply{} }
func (m *ChangePasswordReply) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReply) ProtoMessage()    {}
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *ChangePasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReply.Unmarshal(m, b)
}
func (m *ChangePasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReply.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReply.Merge(m, src)
}
func (m *ChangePasswordReply) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReply.Size(m)
}
func (m *ChangePasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReply proto.InternalMessageInfo

func (m *ChangePasswordReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ChangePasswordReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResetPasswordRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResetPasswordReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordReply) Reset()         { *m = ResetPasswordReply{} }
func (m *ResetPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordReply) ProtoMessage()    {}
func (*ResetPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *ResetPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordReply.Unmarshal(m, b)
}
func (m *ResetPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordReply.Marshal(b, m, deterministic)
}
func (m *ResetPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordReply.Merge(m, src)
}
func (m *ResetPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordReply.Size(m)
}
func (m *ResetPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordReply proto.InternalMessageInfo

func (m *ResetPasswordReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResetPasswordReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetMyselfRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyselfRequest) Reset()         { *m = GetMyselfRequest{} }
func (m *GetMyselfRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyselfRequest) ProtoMessage()    {}
func (*GetMyselfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *GetMyselfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyselfRequest.Unmarshal(m, b)
}
func (m *GetMyselfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyselfRequest.Marshal(b, m, deterministic)
}
func (m *GetMyselfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyselfRequest.Merge(m, src)
}
func (m *GetMyselfRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyselfRequest.Size(m)
}
func (m *GetMyselfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyselfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyselfRequest proto.InternalMessageInfo

type GetMyselfReply struct {
	Data                 *model.Myself `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetMyselfReply) Reset()         { *m = GetMyselfReply{} }
func (m *GetMyselfReply) String() string { return proto.CompactTextString(m) }
func (*GetMyselfReply) ProtoMessage()    {}
func (*GetMyselfReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *GetMyselfReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyselfReply.Unmarshal(m, b)
}
func (m *GetMyselfReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyselfReply.Marshal(b, m, deterministic)
}
func (m *GetMyselfReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyselfReply.Merge(m, src)
}
func (m *GetMyselfReply) XXX_Size() int {
	return xxx_messageInfo_GetMyselfReply.Size(m)
}
func (m *GetMyselfReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyselfReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyselfReply proto.InternalMessageInfo

func (m *GetMyselfReply) GetData() *model.Myself {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetMyselfReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreatePrivilegeProfileRequest struct {
	PrivilegeProfile     *model.PrivilegeProfile `protobuf:"bytes,1,opt,name=privilegeProfile,proto3" json:"privilegeProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreatePrivilegeProfileRequest) Reset()         { *m = CreatePrivilegeProfileRequest{} }
func (m *CreatePrivilegeProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePrivilegeProfileRequest) ProtoMessage()    {}
func (*CreatePrivilegeProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *CreatePrivilegeProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrivilegeProfileRequest.Unmarshal(m, b)
}
func (m *CreatePrivilegeProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrivilegeProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreatePrivilegeProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrivilegeProfileRequest.Merge(m, src)
}
func (m *CreatePrivilegeProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePrivilegeProfileRequest.Size(m)
}
func (m *CreatePrivilegeProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrivilegeProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrivilegeProfileRequest proto.InternalMessageInfo

func (m *CreatePrivilegeProfileRequest) GetPrivilegeProfile() *model.PrivilegeProfile {
	if m != nil {
		return m.PrivilegeProfile
	}
	return nil
}

type CreatePrivilegeProfileReply struct {
	Data                 *model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreatePrivilegeProfileReply) Reset()         { *m = CreatePrivilegeProfileReply{} }
func (m *CreatePrivilegeProfileReply) String() string { return proto.CompactTextString(m) }
func (*CreatePrivilegeProfileReply) ProtoMessage()    {}
func (*CreatePrivilegeProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *CreatePrivilegeProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePrivilegeProfileReply.Unmarshal(m, b)
}
func (m *CreatePrivilegeProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePrivilegeProfileReply.Marshal(b, m, deterministic)
}
func (m *CreatePrivilegeProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePrivilegeProfileReply.Merge(m, src)
}
func (m *CreatePrivilegeProfileReply) XXX_Size() int {
	return xxx_messageInfo_CreatePrivilegeProfileReply.Size(m)
}
func (m *CreatePrivilegeProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePrivilegeProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePrivilegeProfileReply proto.InternalMessageInfo

func (m *CreatePrivilegeProfileReply) GetData() *model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreatePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPrivilegeProfilesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPrivilegeProfilesRequest) Reset()         { *m = GetPrivilegeProfilesRequest{} }
func (m *GetPrivilegeProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrivilegeProfilesRequest) ProtoMessage()    {}
func (*GetPrivilegeProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *GetPrivilegeProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrivilegeProfilesRequest.Unmarshal(m, b)
}
func (m *GetPrivilegeProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrivilegeProfilesRequest.Marshal(b, m, deterministic)
}
func (m *GetPrivilegeProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrivilegeProfilesRequest.Merge(m, src)
}
func (m *GetPrivilegeProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPrivilegeProfilesRequest.Size(m)
}
func (m *GetPrivilegeProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrivilegeProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrivilegeProfilesRequest proto.InternalMessageInfo

type GetPrivilegeProfilesReply struct {
	Data                 map[string]*model.PrivilegeProfile `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string                             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GetPrivilegeProfilesReply) Reset()         { *m = GetPrivilegeProfilesReply{} }
func (m *GetPrivilegeProfilesReply) String() string { return proto.CompactTextString(m) }
func (*GetPrivilegeProfilesReply) ProtoMessage()    {}
func (*GetPrivilegeProfilesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *GetPrivilegeProfilesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrivilegeProfilesReply.Unmarshal(m, b)
}
func (m *GetPrivilegeProfilesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrivilegeProfilesReply.Marshal(b, m, deterministic)
}
func (m *GetPrivilegeProfilesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrivilegeProfilesReply.Merge(m, src)
}
func (m *GetPrivilegeProfilesReply) XXX_Size() int {
	return xxx_messageInfo_GetPrivilegeProfilesReply.Size(m)
}
func (m *GetPrivilegeProfilesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrivilegeProfilesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrivilegeProfilesReply proto.InternalMessageInfo

func (m *GetPrivilegeProfilesReply) GetData() map[string]*model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPrivilegeProfilesReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetPrivilegeProfileByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPrivilegeProfileByIDRequest) Reset()         { *m = GetPrivilegeProfileByIDRequest{} }
func (m *GetPrivilegeProfileByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPrivilegeProfileByIDRequest) ProtoMessage()    {}
func (*GetPrivilegeProfileByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *GetPrivilegeProfileByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrivilegeProfileByIDRequest.Unmarshal(m, b)
}
func (m *GetPrivilegeProfileByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrivilegeProfileByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPrivilegeProfileByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrivilegeProfileByIDRequest.Merge(m, src)
}
func (m *GetPrivilegeProfileByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPrivilegeProfileByIDRequest.Size(m)
}
func (m *GetPrivilegeProfileByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrivilegeProfileByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrivilegeProfileByIDRequest proto.InternalMessageInfo

func (m *GetPrivilegeProfileByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPrivilegeProfileByIDReply struct {
	Data                 *model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetPrivilegeProfileByIDReply) Reset()         { *m = GetPrivilegeProfileByIDReply{} }
func (m *GetPrivilegeProfileByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetPrivilegeProfileByIDReply) ProtoMessage()    {}
func (*GetPrivilegeProfileByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *GetPrivilegeProfileByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPrivilegeProfileByIDReply.Unmarshal(m, b)
}
func (m *GetPrivilegeProfileByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPrivilegeProfileByIDReply.Marshal(b, m, deterministic)
}
func (m *GetPrivilegeProfileByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPrivilegeProfileByIDReply.Merge(m, src)
}
func (m *GetPrivilegeProfileByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetPrivilegeProfileByIDReply.Size(m)
}
func (m *GetPrivilegeProfileByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPrivilegeProfileByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPrivilegeProfileByIDReply proto.InternalMessageInfo

func (m *GetPrivilegeProfileByIDReply) GetData() *model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPrivilegeProfileByIDReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdatePrivilegeProfileRequest struct {
	PrivilegeProfile     *model.PrivilegeProfile `protobuf:"bytes,1,opt,name=privilegeProfile,proto3" json:"privilegeProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdatePrivilegeProfileRequest) Reset()         { *m = UpdatePrivilegeProfileRequest{} }
func (m *UpdatePrivilegeProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePrivilegeProfileRequest) ProtoMessage()    {}
func (*UpdatePrivilegeProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{24}
}

func (m *UpdatePrivilegeProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrivilegeProfileRequest.Unmarshal(m, b)
}
func (m *UpdatePrivilegeProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrivilegeProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePrivilegeProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrivilegeProfileRequest.Merge(m, src)
}
func (m *UpdatePrivilegeProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePrivilegeProfileRequest.Size(m)
}
func (m *UpdatePrivilegeProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrivilegeProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrivilegeProfileRequest proto.InternalMessageInfo

func (m *UpdatePrivilegeProfileRequest) GetPrivilegeProfile() *model.PrivilegeProfile {
	if m != nil {
		return m.PrivilegeProfile
	}
	return nil
}

type UpdatePrivilegeProfileReply struct {
	Data                 *model.PrivilegeProfile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdatePrivilegeProfileReply) Reset()         { *m = UpdatePrivilegeProfileReply{} }
func (m *UpdatePrivilegeProfileReply) String() string { return proto.CompactTextString(m) }
func (*UpdatePrivilegeProfileReply) ProtoMessage()    {}
func (*UpdatePrivilegeProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{25}
}

func (m *UpdatePrivilegeProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrivilegeProfileReply.Unmarshal(m, b)
}
func (m *UpdatePrivilegeProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrivilegeProfileReply.Marshal(b, m, deterministic)
}
func (m *UpdatePrivilegeProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrivilegeProfileReply.Merge(m, src)
}
func (m *UpdatePrivilegeProfileReply) XXX_Size() int {
	return xxx_messageInfo_UpdatePrivilegeProfileReply.Size(m)
}
func (m *UpdatePrivilegeProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrivilegeProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrivilegeProfileReply proto.InternalMessageInfo

func (m *UpdatePrivilegeProfileReply) GetData() *model.PrivilegeProfile {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdatePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeletePrivilegeProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePrivilegeProfileRequest) Reset()         { *m = DeletePrivilegeProfileRequest{} }
func (m *DeletePrivilegeProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePrivilegeProfileRequest) ProtoMessage()    {}
func (*DeletePrivilegeProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{26}
}

func (m *DeletePrivilegeProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePrivilegeProfileRequest.Unmarshal(m, b)
}
func (m *DeletePrivilegeProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePrivilegeProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeletePrivilegeProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePrivilegeProfileRequest.Merge(m, src)
}
func (m *DeletePrivilegeProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePrivilegeProfileRequest.Size(m)
}
func (m *DeletePrivilegeProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePrivilegeProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePrivilegeProfileRequest proto.InternalMessageInfo

func (m *DeletePrivilegeProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePrivilegeProfileReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePrivilegeProfileReply) Reset()         { *m = DeletePrivilegeProfileReply{} }
func (m *DeletePrivilegeProfileReply) String() string { return proto.CompactTextString(m) }
func (*DeletePrivilegeProfileReply) ProtoMessage()    {}
func (*DeletePrivilegeProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{27}
}

func (m *DeletePrivilegeProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePrivilegeProfileReply.Unmarshal(m, b)
}
func (m *DeletePrivilegeProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePrivilegeProfileReply.Marshal(b, m, deterministic)
}
func (m *DeletePrivilegeProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePrivilegeProfileReply.Merge(m, src)
}
func (m *DeletePrivilegeProfileReply) XXX_Size() int {
	return xxx_messageInfo_DeletePrivilegeProfileReply.Size(m)
}
func (m *DeletePrivilegeProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePrivilegeProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePrivilegeProfileReply proto.InternalMessageInfo

func (m *DeletePrivilegeProfileReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DeletePrivilegeProfileReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetLocationTreeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocationTreeRequest) Reset()         { *m = GetLocationTreeRequest{} }
func (m *GetLocationTreeRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocationTreeRequest) ProtoMessage()    {}
func (*GetLocationTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{28}
}

func (m *GetLocationTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocationTreeRequest.Unmarshal(m, b)
}
func (m *GetLocationTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocationTreeRequest.Marshal(b, m, deterministic)
}
func (m *GetLocationTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocationTreeRequest.Merge(m, src)
}
func (m *GetLocationTreeRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocationTreeRequest.Size(m)
}
func (m *GetLocationTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocationTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocationTreeRequest proto.InternalMessageInfo

type GetLocationTreeReply struct {
	Data                 []*model.LocationNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetLocationTreeReply) Reset()         { *m = GetLocationTreeReply{} }
func (m *GetLocationTreeReply) String() string { return proto.CompactTextString(m) }
func (*GetLocationTreeReply) ProtoMessage()    {}
func (*GetLocationTreeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{29}
}

func (m *GetLocationTreeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocationTreeReply.Unmarshal(m, b)
}
func (m *GetLocationTreeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocationTreeReply.Marshal(b, m, deterministic)
}
func (m *GetLocationTreeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocationTreeReply.Merge(m, src)
}
func (m *GetLocationTreeReply) XXX_Size() int {
	return xxx_messageInfo_GetLocationTreeReply.Size(m)
}
func (m *GetLocationTreeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocationTreeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocationTreeReply proto.InternalMessageInfo

func (m *GetLocationTreeReply) GetData() []*model.LocationNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetLocationTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateLocationTreeRequest struct {
	Locations            []*model.LocationNode `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateLocationTreeRequest) Reset()         { *m = UpdateLocationTreeRequest{} }
func (m *UpdateLocationTreeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationTreeRequest) ProtoMessage()    {}
func (*UpdateLocationTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{30}
}

func (m *UpdateLocationTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationTreeRequest.Unmarshal(m, b)
}
func (m *UpdateLocationTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationTreeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLocationTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationTreeRequest.Merge(m, src)
}
func (m *UpdateLocationTreeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationTreeRequest.Size(m)
}
func (m *UpdateLocationTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationTreeRequest proto.InternalMessageInfo

func (m *UpdateLocationTreeRequest) GetLocations() []*model.LocationNode {
	if m != nil {
		return m.Locations
	}
	return nil
}

type UpdateLocationTreeReply struct {
	Data                 []*model.LocationNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateLocationTreeReply) Reset()         { *m = UpdateLocationTreeReply{} }
func (m *UpdateLocationTreeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateLocationTreeReply) ProtoMessage()    {}
func (*UpdateLocationTreeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{31}
}

func (m *UpdateLocationTreeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLocationTreeReply.Unmarshal(m, b)
}
func (m *UpdateLocationTreeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLocationTreeReply.Marshal(b, m, deterministic)
}
func (m *UpdateLocationTreeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLocationTreeReply.Merge(m, src)
}
func (m *UpdateLocationTreeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateLocationTreeReply.Size(m)
}
func (m *UpdateLocationTreeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLocationTreeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLocationTreeReply proto.InternalMessageInfo

func (m *UpdateLocationTreeReply) GetData() []*model.LocationNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateLocationTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetScopeTreeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScopeTreeRequest) Reset()         { *m = GetScopeTreeRequest{} }
func (m *GetScopeTreeRequest) String() string { return proto.CompactTextString(m) }
func (*GetScopeTreeRequest) ProtoMessage()    {}
func (*GetScopeTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{32}
}

func (m *GetScopeTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScopeTreeRequest.Unmarshal(m, b)
}
func (m *GetScopeTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScopeTreeRequest.Marshal(b, m, deterministic)
}
func (m *GetScopeTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScopeTreeRequest.Merge(m, src)
}
func (m *GetScopeTreeRequest) XXX_Size() int {
	return xxx_messageInfo_GetScopeTreeRequest.Size(m)
}
func (m *GetScopeTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScopeTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScopeTreeRequest proto.InternalMessageInfo

type GetScopeTreeReply struct {
	Data                 []*model.ScopeNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                string             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetScopeTreeReply) Reset()         { *m = GetScopeTreeReply{} }
func (m *GetScopeTreeReply) String() string { return proto.CompactTextString(m) }
func (*GetScopeTreeReply) ProtoMessage()    {}
func (*GetScopeTreeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{33}
}

func (m *GetScopeTreeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScopeTreeReply.Unmarshal(m, b)
}
func (m *GetScopeTreeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScopeTreeReply.Marshal(b, m, deterministic)
}
func (m *GetScopeTreeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScopeTreeReply.Merge(m, src)
}
func (m *GetScopeTreeReply) XXX_Size() int {
	return xxx_messageInfo_GetScopeTreeReply.Size(m)
}
func (m *GetScopeTreeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScopeTreeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetScopeTreeReply proto.InternalMessageInfo

func (m *GetScopeTreeReply) GetData() []*model.ScopeNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetScopeTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateScopeTreeRequest struct {
	Scopes               []*model.ScopeNode `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateScopeTreeRequest) Reset()         { *m = UpdateScopeTreeRequest{} }
func (m *UpdateScopeTreeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateScopeTreeRequest) ProtoMessage()    {}
func (*UpdateScopeTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{34}
}

func (m *UpdateScopeTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScopeTreeRequest.Unmarshal(m, b)
}
func (m *UpdateScopeTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScopeTreeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateScopeTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScopeTreeRequest.Merge(m, src)
}
func (m *UpdateScopeTreeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateScopeTreeRequest.Size(m)
}
func (m *UpdateScopeTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScopeTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScopeTreeRequest proto.InternalMessageInfo

func (m *UpdateScopeTreeRequest) GetScopes() []*model.ScopeNode {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type UpdateScopeTreeReply struct {
	Data                 []*model.ScopeNode `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                string             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateScopeTreeReply) Reset()         { *m = UpdateScopeTreeReply{} }
func (m *UpdateScopeTreeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateScopeTreeReply) ProtoMessage()    {}
func (*UpdateScopeTreeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{35}
}

func (m *UpdateScopeTreeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScopeTreeReply.Unmarshal(m, b)
}
func (m *UpdateScopeTreeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScopeTreeReply.Marshal(b, m, deterministic)
}
func (m *UpdateScopeTreeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScopeTreeReply.Merge(m, src)
}
func (m *UpdateScopeTreeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateScopeTreeReply.Size(m)
}
func (m *UpdateScopeTreeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScopeTreeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScopeTreeReply proto.InternalMessageInfo

func (m *UpdateScopeTreeReply) GetData() []*model.ScopeNode {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateScopeTreeReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangeVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeVersionRequest) Reset()         { *m = ChangeVersionRequest{} }
func (m *ChangeVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeVersionRequest) ProtoMessage()    {}
func (*ChangeVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{36}
}

func (m *ChangeVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeVersionRequest.Unmarshal(m, b)
}
func (m *ChangeVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeVersionRequest.Marshal(b, m, deterministic)
}
func (m *ChangeVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeVersionRequest.Merge(m, src)
}
func (m *ChangeVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeVersionRequest.Size(m)
}
func (m *ChangeVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeVersionRequest proto.InternalMessageInfo

type ChangeVersionReply struct {
	Data                 *model.ChangeVersion `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangeVersionReply) Reset()         { *m = ChangeVersionReply{} }
func (m *ChangeVersionReply) String() string { return proto.CompactTextString(m) }
func (*ChangeVersionReply) ProtoMessage()    {}
func (*ChangeVersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{37}
}

func (m *ChangeVersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeVersionReply.Unmarshal(m, b)
}
func (m *ChangeVersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeVersionReply.Marshal(b, m, deterministic)
}
func (m *ChangeVersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeVersionReply.Merge(m, src)
}
func (m *ChangeVersionReply) XXX_Size() int {
	return xxx_messageInfo_ChangeVersionReply.Size(m)
}
func (m *ChangeVersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeVersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeVersionReply proto.InternalMessageInfo

func (m *ChangeVersionReply) GetData() *model.ChangeVersion {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChangeVersionReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type TopicAllMessage struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicAllMessage) Reset()         { *m = TopicAllMessage{} }
func (m *TopicAllMessage) String() string { return proto.CompactTextString(m) }
func (*TopicAllMessage) ProtoMessage()    {}
func (*TopicAllMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{38}
}

func (m *TopicAllMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicAllMessage.Unmarshal(m, b)
}
func (m *TopicAllMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicAllMessage.Marshal(b, m, deterministic)
}
func (m *TopicAllMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicAllMessage.Merge(m, src)
}
func (m *TopicAllMessage) XXX_Size() int {
	return xxx_messageInfo_TopicAllMessage.Size(m)
}
func (m *TopicAllMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicAllMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicAllMessage proto.InternalMessageInfo

func (m *TopicAllMessage) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *TopicAllMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "creapptive.message.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "creapptive.message.LoginReply")
	proto.RegisterType((*CreateUserRequest)(nil), "creapptive.message.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "creapptive.message.CreateUserReply")
	proto.RegisterType((*GetUsersRequest)(nil), "creapptive.message.GetUsersRequest")
	proto.RegisterType((*GetUsersReply)(nil), "creapptive.message.GetUsersReply")
	proto.RegisterMapType((map[string]*model.User)(nil), "creapptive.message.GetUsersReply.DataEntry")
	proto.RegisterType((*GetUserByIDRequest)(nil), "creapptive.message.GetUserByIDRequest")
	proto.RegisterType((*GetUserByIDReply)(nil), "creapptive.message.GetUserByIDReply")
	proto.RegisterType((*UpdateUserRequest)(nil), "creapptive.message.UpdateUserRequest")
	proto.RegisterType((*UpdateUserReply)(nil), "creapptive.message.UpdateUserReply")
	proto.RegisterType((*DeleteUserRequest)(nil), "creapptive.message.DeleteUserRequest")
	proto.RegisterType((*DeleteUserReply)(nil), "creapptive.message.DeleteUserReply")
	proto.RegisterType((*ChangePasswordRequest)(nil), "creapptive.message.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordReply)(nil), "creapptive.message.ChangePasswordReply")
	proto.RegisterType((*ResetPasswordRequest)(nil), "creapptive.message.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordReply)(nil), "creapptive.message.ResetPasswordReply")
	proto.RegisterType((*GetMyselfRequest)(nil), "creapptive.message.GetMyselfRequest")
	proto.RegisterType((*GetMyselfReply)(nil), "creapptive.message.GetMyselfReply")
	proto.RegisterType((*CreatePrivilegeProfileRequest)(nil), "creapptive.message.CreatePrivilegeProfileRequest")
	proto.RegisterType((*CreatePrivilegeProfileReply)(nil), "creapptive.message.CreatePrivilegeProfileReply")
	proto.RegisterType((*GetPrivilegeProfilesRequest)(nil), "creapptive.message.GetPrivilegeProfilesRequest")
	proto.RegisterType((*GetPrivilegeProfilesReply)(nil), "creapptive.message.GetPrivilegeProfilesReply")
	proto.RegisterMapType((map[string]*model.PrivilegeProfile)(nil), "creapptive.message.GetPrivilegeProfilesReply.DataEntry")
	proto.RegisterType((*GetPrivilegeProfileByIDRequest)(nil), "creapptive.message.GetPrivilegeProfileByIDRequest")
	proto.RegisterType((*GetPrivilegeProfileByIDReply)(nil), "creapptive.message.GetPrivilegeProfileByIDReply")
	proto.RegisterType((*UpdatePrivilegeProfileRequest)(nil), "creapptive.message.UpdatePrivilegeProfileRequest")
	proto.RegisterType((*UpdatePrivilegeProfileReply)(nil), "creapptive.message.UpdatePrivilegeProfileReply")
	proto.RegisterType((*DeletePrivilegeProfileRequest)(nil), "creapptive.message.DeletePrivilegeProfileRequest")
	proto.RegisterType((*DeletePrivilegeProfileReply)(nil), "creapptive.message.DeletePrivilegeProfileReply")
	proto.RegisterType((*GetLocationTreeRequest)(nil), "creapptive.message.GetLocationTreeRequest")
	proto.RegisterType((*GetLocationTreeReply)(nil), "creapptive.message.GetLocationTreeReply")
	proto.RegisterType((*UpdateLocationTreeRequest)(nil), "creapptive.message.UpdateLocationTreeRequest")
	proto.RegisterType((*UpdateLocationTreeReply)(nil), "creapptive.message.UpdateLocationTreeReply")
	proto.RegisterType((*GetScopeTreeRequest)(nil), "creapptive.message.GetScopeTreeRequest")
	proto.RegisterType((*GetScopeTreeReply)(nil), "creapptive.message.GetScopeTreeReply")
	proto.RegisterType((*UpdateScopeTreeRequest)(nil), "creapptive.message.UpdateScopeTreeRequest")
	proto.RegisterType((*UpdateScopeTreeReply)(nil), "creapptive.message.UpdateScopeTreeReply")
	proto.RegisterType((*ChangeVersionRequest)(nil), "creapptive.message.ChangeVersionRequest")
	proto.RegisterType((*ChangeVersionReply)(nil), "creapptive.message.ChangeVersionReply")
	proto.RegisterType((*TopicAllMessage)(nil), "creapptive.message.TopicAllMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x7f, 0x4f, 0x13, 0x4b,
	0x14, 0x4d, 0xcb, 0x8f, 0xbc, 0xde, 0x3e, 0x28, 0x1d, 0x4a, 0x5f, 0xa1, 0xaf, 0x3c, 0x32, 0xef,
	0xe5, 0x89, 0x88, 0xad, 0x81, 0x44, 0x89, 0x18, 0x1b, 0x01, 0x6d, 0x8c, 0x80, 0x4d, 0x29, 0x26,
	0x62, 0x8c, 0xae, 0xdd, 0x4b, 0xdd, 0xb0, 0xed, 0xac, 0x33, 0xd3, 0x92, 0x7e, 0x32, 0x3f, 0x8c,
	0x5f, 0xc6, 0xec, 0xee, 0xb4, 0xec, 0x8f, 0xee, 0x52, 0x62, 0xe3, 0x7f, 0xcc, 0x9d, 0x73, 0xef,
	0x39, 0xf7, 0xce, 0xde, 0x03, 0xc0, 0x42, 0x07, 0x85, 0xd0, 0xda, 0x58, 0xb6, 0x38, 0x93, 0x8c,
	0x90, 0x16, 0x47, 0xcd, 0xb2, 0xa4, 0xd1, 0xc7, 0xb2, 0xba, 0x59, 0x4b, 0x77, 0x98, 0x8e, 0xa6,
	0x0b, 0xa0, 0xaf, 0xe0, 0xcf, 0x63, 0xd6, 0x36, 0xba, 0x0d, 0xfc, 0xd6, 0x43, 0x21, 0xc9, 0x1a,
	0xfc, 0xd1, 0x13, 0xc8, 0xbb, 0x5a, 0x07, 0x0b, 0x89, 0x8d, 0xc4, 0x66, 0xaa, 0x31, 0x3a, 0xdb,
	0x77, 0x96, 0x26, 0xc4, 0x35, 0xe3, 0x7a, 0x21, 0xe9, 0xde, 0x0d, 0xcf, 0xb4, 0x0e, 0xa0, 0xea,
	0x58, 0xe6, 0x80, 0x6c, 0xc3, 0xac, 0xae, 0x49, 0xcd, 0xa9, 0x90, 0xde, 0x29, 0x94, 0xbd, 0x2a,
	0x1c, 0xf2, 0x93, 0x81, 0x40, 0xf3, 0xb2, 0xe1, 0xa0, 0x48, 0x0e, 0xe6, 0x90, 0x73, 0xc6, 0x55,
	0x51, 0xf7, 0x40, 0xab, 0x90, 0x3d, 0xe4, 0xa8, 0x49, 0x3c, 0x17, 0xc8, 0x87, 0xf2, 0xb6, 0x60,
	0xd6, 0x96, 0xa3, 0x0a, 0xe7, 0xc3, 0x85, 0x1d, 0xb0, 0x83, 0xa1, 0x67, 0x90, 0xf1, 0x16, 0xb0,
	0x75, 0x6d, 0xf9, 0x74, 0x45, 0xa6, 0xc7, 0xa8, 0xca, 0x42, 0xa6, 0x86, 0xd2, 0x86, 0x09, 0xa5,
	0x89, 0x7e, 0x4f, 0xc0, 0xc2, 0x4d, 0xcc, 0xa6, 0xa9, 0x8e, 0x68, 0x66, 0x36, 0xd3, 0x3b, 0x0f,
	0xca, 0xe1, 0x47, 0x28, 0xfb, 0x12, 0xca, 0x47, 0x9a, 0xd4, 0x5e, 0x76, 0x25, 0x1f, 0xc4, 0x71,
	0xaf, 0xbd, 0x85, 0xd4, 0x08, 0x48, 0x96, 0x60, 0xe6, 0x0a, 0x07, 0xea, 0x8d, 0xec, 0x1f, 0xc9,
	0x36, 0xcc, 0xf5, 0x35, 0xb3, 0x87, 0x4e, 0x52, 0x74, 0x77, 0x2e, 0xe8, 0x69, 0x72, 0x2f, 0x41,
	0xff, 0x03, 0xa2, 0x74, 0x1c, 0x0c, 0x5e, 0x1f, 0x0d, 0x67, 0xbc, 0x08, 0x49, 0x43, 0x57, 0x85,
	0x93, 0x86, 0x4e, 0x9b, 0xb0, 0xe4, 0x43, 0x4d, 0x67, 0x90, 0x55, 0xc8, 0x9e, 0x5b, 0xfa, 0xaf,
	0x3d, 0xaf, 0xb7, 0xc0, 0x74, 0x54, 0xfd, 0x0b, 0xd9, 0x23, 0x34, 0xd1, 0xaf, 0x2a, 0x38, 0x90,
	0x7d, 0xc8, 0x78, 0x41, 0x36, 0x33, 0xf1, 0x30, 0xa7, 0x62, 0x19, 0xae, 0x60, 0xe5, 0xf0, 0xab,
	0xd6, 0x6d, 0x63, 0x5d, 0xad, 0x4e, 0x04, 0x0b, 0xd9, 0x80, 0x34, 0x33, 0xf5, 0xba, 0x7f, 0xe1,
	0xbc, 0x21, 0x1b, 0xd1, 0xc5, 0xeb, 0x11, 0x62, 0xc6, 0x45, 0x78, 0x42, 0xb4, 0x0a, 0xcb, 0x41,
	0xb2, 0xbb, 0xa9, 0xfd, 0x1f, 0x72, 0x0d, 0x14, 0x28, 0x6f, 0x11, 0x4b, 0x9f, 0x03, 0x09, 0xe0,
	0xee, 0xc6, 0x43, 0x9c, 0x6f, 0x4c, 0xb9, 0x82, 0xda, 0xab, 0x26, 0x2c, 0x7a, 0x62, 0xd3, 0xb2,
	0x15, 0x06, 0x25, 0xd7, 0x15, 0xea, 0xdc, 0xe8, 0x1b, 0x26, 0xb6, 0xb1, 0xce, 0xd9, 0xa5, 0x61,
	0xe2, 0xb0, 0xb5, 0x53, 0x58, 0xb2, 0x02, 0x57, 0x8a, 0x90, 0x86, 0x09, 0x43, 0x45, 0x42, 0xb9,
	0xf4, 0x0a, 0x8a, 0x51, 0x84, 0x76, 0x4f, 0x8f, 0x7d, 0x3d, 0x4d, 0x42, 0x11, 0xd7, 0x5d, 0x09,
	0x8a, 0x35, 0x94, 0xc1, 0x94, 0x91, 0x55, 0xfd, 0x48, 0xc0, 0xea, 0xf8, 0x7b, 0x5b, 0xca, 0x1b,
	0x9f, 0x6d, 0x3d, 0x89, 0xb0, 0xad, 0xf1, 0xc9, 0x13, 0x5a, 0xd8, 0x87, 0x78, 0x0b, 0xdb, 0xf3,
	0x5b, 0xd8, 0x24, 0xd3, 0xf0, 0xd8, 0xd9, 0x23, 0x58, 0x1f, 0xa3, 0x2f, 0xce, 0xda, 0x4c, 0xf8,
	0x3b, 0x32, 0x63, 0xfa, 0x8f, 0xc3, 0xa0, 0xe4, 0x3a, 0xd6, 0x6f, 0xfc, 0xf4, 0xa2, 0x08, 0xa7,
	0xdf, 0x5d, 0x05, 0x4a, 0xae, 0x2b, 0x46, 0x75, 0x17, 0x1c, 0x7e, 0x0d, 0x8a, 0x51, 0x09, 0x77,
	0x33, 0x8f, 0x02, 0xe4, 0x6b, 0x28, 0x8f, 0x59, 0x4b, 0x93, 0x06, 0xeb, 0x36, 0x39, 0x0e, 0x29,
	0xe9, 0x67, 0xc8, 0x85, 0x6e, 0xec, 0xda, 0x3b, 0xbe, 0x2f, 0x7d, 0x3d, 0xdc, 0xf9, 0x30, 0xe5,
	0x94, 0xe9, 0xf1, 0x5d, 0xbf, 0x87, 0x55, 0x77, 0xc4, 0x63, 0xe8, 0xc9, 0x33, 0x48, 0x99, 0x2a,
	0x2c, 0x26, 0xe4, 0xba, 0x49, 0xa0, 0x2d, 0xf8, 0x6b, 0x5c, 0xe9, 0xe9, 0xea, 0x5f, 0x81, 0xe5,
	0x1a, 0xca, 0xb3, 0x16, 0xb3, 0xd0, 0x3b, 0xb8, 0x0b, 0xc8, 0xfa, 0xc3, 0x36, 0x6b, 0xc5, 0xc7,
	0x5a, 0x0c, 0xb3, 0x3a, 0xf8, 0x5b, 0x29, 0x4f, 0x20, 0xef, 0xf6, 0x15, 0x64, 0x25, 0xbb, 0x30,
	0x2f, 0xec, 0x98, 0x98, 0x84, 0x42, 0x41, 0xe9, 0x47, 0xc8, 0x85, 0xca, 0x4d, 0x51, 0x6d, 0x1e,
	0x72, 0xee, 0xaf, 0xd0, 0x77, 0xc8, 0x85, 0xc1, 0x86, 0x7f, 0x28, 0xd3, 0x4f, 0x40, 0x02, 0x71,
	0x9b, 0x74, 0xd7, 0xb7, 0x52, 0xff, 0x84, 0x49, 0xfd, 0x39, 0x71, 0xc4, 0xfb, 0x90, 0x69, 0x32,
	0xcb, 0x68, 0xbd, 0x30, 0xcd, 0x13, 0xd7, 0x7d, 0x1d, 0x60, 0x1f, 0xbb, 0x52, 0xed, 0x84, 0x7b,
	0x18, 0x2d, 0x4a, 0xf2, 0x66, 0x51, 0x0e, 0xee, 0x5f, 0xdc, 0xf3, 0x50, 0xb7, 0x58, 0xa7, 0x62,
	0x74, 0xc4, 0x43, 0x81, 0xad, 0x1e, 0x37, 0xe4, 0xa0, 0xa2, 0x59, 0x46, 0x45, 0x59, 0xfa, 0x97,
	0x79, 0xe7, 0x1f, 0x81, 0xdd, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45, 0xea, 0x1d, 0x78, 0x3a,
	0x0c, 0x00, 0x00,
}
