version: '3.7'
services:
  # API gateway provide the entry point to the servers
  #FIXME

  # authen service provide authentication service
  #FIXME

  # user service provide user info service
  #FIXME

  #
  # mongodb
  #
  database:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${IMS_DATABASE_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${IMS_DATABASE_ROOT_PASSWORD}
      - IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_DBNAME=${IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_DBNAME}
      - IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_USER=${IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_USER}
      - IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_PASSWORD=${IMS_SECURITY_SERVICE_APIGATEWAY_DATABASE_PASSWORD}
      - IMS_SECURITY_SERVICE_AUTHEN_DATABASE_DBNAME=${IMS_SECURITY_SERVICE_AUTHEN_DATABASE_DBNAME}
      - IMS_SECURITY_SERVICE_AUTHEN_DATABASE_USER=${IMS_SECURITY_SERVICE_AUTHEN_DATABASE_USER}
      - IMS_SECURITY_SERVICE_AUTHEN_DATABASE_PASSWORD=${IMS_SECURITY_SERVICE_AUTHEN_DATABASE_PASSWORD}
      - IMS_SECURITY_SERVICE_USER_DATABASE_DBNAME=${IMS_SECURITY_SERVICE_USER_DATABASE_DBNAME}
      - IMS_SECURITY_SERVICE_USER_DATABASE_USER=${IMS_SECURITY_SERVICE_USER_DATABASE_USER}
      - IMS_SECURITY_SERVICE_USER_DATABASE_PASSWORD=${IMS_SECURITY_SERVICE_USER_DATABASE_PASSWORD}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data_container:
