// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apigateway.proto

/*
Package apigateway is a generated protocol buffer package.

It is generated from these files:
	apigateway.proto

It has these top-level messages:
	ApigatewayMessage
*/
package apigateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import creapptive_message "creapptive.com/ims-security/api/message"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApigatewayMessage struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
}

func (m *ApigatewayMessage) Reset()                    { *m = ApigatewayMessage{} }
func (m *ApigatewayMessage) String() string            { return proto.CompactTextString(m) }
func (*ApigatewayMessage) ProtoMessage()               {}
func (*ApigatewayMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApigatewayMessage) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func init() {
	proto.RegisterType((*ApigatewayMessage)(nil), "creapptive.api.ApigatewayMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Apigateway service

type ApigatewayClient interface {
	Login(ctx context.Context, in *creapptive_message.LoginRequest, opts ...grpc.CallOption) (*creapptive_message.LoginReply, error)
	CreateUser(ctx context.Context, in *creapptive_message.CreateUserRequest, opts ...grpc.CallOption) (*creapptive_message.CreateUserReply, error)
	GetUsers(ctx context.Context, in *creapptive_message.GetUsersRequest, opts ...grpc.CallOption) (*creapptive_message.GetUsersReply, error)
	GetUserByID(ctx context.Context, in *creapptive_message.GetUserByIDRequest, opts ...grpc.CallOption) (*creapptive_message.GetUserByIDReply, error)
	UpdateUser(ctx context.Context, in *creapptive_message.UpdateUserRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateUserReply, error)
	DeleteUser(ctx context.Context, in *creapptive_message.DeleteUserRequest, opts ...grpc.CallOption) (*creapptive_message.DeleteUserReply, error)
	ChangePassword(ctx context.Context, in *creapptive_message.ChangePasswordRequest, opts ...grpc.CallOption) (*creapptive_message.ChangePasswordReply, error)
	ResetPassword(ctx context.Context, in *creapptive_message.ResetPasswordRequest, opts ...grpc.CallOption) (*creapptive_message.ResetPasswordReply, error)
	GetMyself(ctx context.Context, in *creapptive_message.GetMyselfRequest, opts ...grpc.CallOption) (*creapptive_message.GetMyselfReply, error)
	CreatePrivilegeProfile(ctx context.Context, in *creapptive_message.CreatePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.CreatePrivilegeProfileReply, error)
	GetPrivilegeProfiles(ctx context.Context, in *creapptive_message.GetPrivilegeProfilesRequest, opts ...grpc.CallOption) (*creapptive_message.GetPrivilegeProfilesReply, error)
	GetPrivilegeProfileByID(ctx context.Context, in *creapptive_message.GetPrivilegeProfileByIDRequest, opts ...grpc.CallOption) (*creapptive_message.GetPrivilegeProfileByIDReply, error)
	UpdatePrivilegeProfile(ctx context.Context, in *creapptive_message.UpdatePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.UpdatePrivilegeProfileReply, error)
	DeletePrivilegeProfile(ctx context.Context, in *creapptive_message.DeletePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.DeletePrivilegeProfileReply, error)
	GetLocationTree(ctx context.Context, in *creapptive_message.GetLocationTreeRequest, opts ...grpc.CallOption) (*creapptive_message.GetLocationTreeReply, error)
	UpdateLocationTree(ctx context.Context, in *creapptive_message.UpdateLocationTreeRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateLocationTreeReply, error)
	GetScopeTree(ctx context.Context, in *creapptive_message.GetScopeTreeRequest, opts ...grpc.CallOption) (*creapptive_message.GetScopeTreeReply, error)
	UpdateScopeTree(ctx context.Context, in *creapptive_message.UpdateScopeTreeRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateScopeTreeReply, error)
	ChangeVersion(ctx context.Context, in *creapptive_message.ChangeVersionRequest, opts ...grpc.CallOption) (*creapptive_message.ChangeVersionReply, error)
}

type apigatewayClient struct {
	cc *grpc.ClientConn
}

func NewApigatewayClient(cc *grpc.ClientConn) ApigatewayClient {
	return &apigatewayClient{cc}
}

func (c *apigatewayClient) Login(ctx context.Context, in *creapptive_message.LoginRequest, opts ...grpc.CallOption) (*creapptive_message.LoginReply, error) {
	out := new(creapptive_message.LoginReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) CreateUser(ctx context.Context, in *creapptive_message.CreateUserRequest, opts ...grpc.CallOption) (*creapptive_message.CreateUserReply, error) {
	out := new(creapptive_message.CreateUserReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetUsers(ctx context.Context, in *creapptive_message.GetUsersRequest, opts ...grpc.CallOption) (*creapptive_message.GetUsersReply, error) {
	out := new(creapptive_message.GetUsersReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetUserByID(ctx context.Context, in *creapptive_message.GetUserByIDRequest, opts ...grpc.CallOption) (*creapptive_message.GetUserByIDReply, error) {
	out := new(creapptive_message.GetUserByIDReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetUserByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) UpdateUser(ctx context.Context, in *creapptive_message.UpdateUserRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateUserReply, error) {
	out := new(creapptive_message.UpdateUserReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) DeleteUser(ctx context.Context, in *creapptive_message.DeleteUserRequest, opts ...grpc.CallOption) (*creapptive_message.DeleteUserReply, error) {
	out := new(creapptive_message.DeleteUserReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) ChangePassword(ctx context.Context, in *creapptive_message.ChangePasswordRequest, opts ...grpc.CallOption) (*creapptive_message.ChangePasswordReply, error) {
	out := new(creapptive_message.ChangePasswordReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/ChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) ResetPassword(ctx context.Context, in *creapptive_message.ResetPasswordRequest, opts ...grpc.CallOption) (*creapptive_message.ResetPasswordReply, error) {
	out := new(creapptive_message.ResetPasswordReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/ResetPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetMyself(ctx context.Context, in *creapptive_message.GetMyselfRequest, opts ...grpc.CallOption) (*creapptive_message.GetMyselfReply, error) {
	out := new(creapptive_message.GetMyselfReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetMyself", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) CreatePrivilegeProfile(ctx context.Context, in *creapptive_message.CreatePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.CreatePrivilegeProfileReply, error) {
	out := new(creapptive_message.CreatePrivilegeProfileReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/CreatePrivilegeProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetPrivilegeProfiles(ctx context.Context, in *creapptive_message.GetPrivilegeProfilesRequest, opts ...grpc.CallOption) (*creapptive_message.GetPrivilegeProfilesReply, error) {
	out := new(creapptive_message.GetPrivilegeProfilesReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetPrivilegeProfiles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetPrivilegeProfileByID(ctx context.Context, in *creapptive_message.GetPrivilegeProfileByIDRequest, opts ...grpc.CallOption) (*creapptive_message.GetPrivilegeProfileByIDReply, error) {
	out := new(creapptive_message.GetPrivilegeProfileByIDReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetPrivilegeProfileByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) UpdatePrivilegeProfile(ctx context.Context, in *creapptive_message.UpdatePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.UpdatePrivilegeProfileReply, error) {
	out := new(creapptive_message.UpdatePrivilegeProfileReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/UpdatePrivilegeProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) DeletePrivilegeProfile(ctx context.Context, in *creapptive_message.DeletePrivilegeProfileRequest, opts ...grpc.CallOption) (*creapptive_message.DeletePrivilegeProfileReply, error) {
	out := new(creapptive_message.DeletePrivilegeProfileReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/DeletePrivilegeProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetLocationTree(ctx context.Context, in *creapptive_message.GetLocationTreeRequest, opts ...grpc.CallOption) (*creapptive_message.GetLocationTreeReply, error) {
	out := new(creapptive_message.GetLocationTreeReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetLocationTree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) UpdateLocationTree(ctx context.Context, in *creapptive_message.UpdateLocationTreeRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateLocationTreeReply, error) {
	out := new(creapptive_message.UpdateLocationTreeReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/UpdateLocationTree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) GetScopeTree(ctx context.Context, in *creapptive_message.GetScopeTreeRequest, opts ...grpc.CallOption) (*creapptive_message.GetScopeTreeReply, error) {
	out := new(creapptive_message.GetScopeTreeReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/GetScopeTree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) UpdateScopeTree(ctx context.Context, in *creapptive_message.UpdateScopeTreeRequest, opts ...grpc.CallOption) (*creapptive_message.UpdateScopeTreeReply, error) {
	out := new(creapptive_message.UpdateScopeTreeReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/UpdateScopeTree", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apigatewayClient) ChangeVersion(ctx context.Context, in *creapptive_message.ChangeVersionRequest, opts ...grpc.CallOption) (*creapptive_message.ChangeVersionReply, error) {
	out := new(creapptive_message.ChangeVersionReply)
	err := grpc.Invoke(ctx, "/creapptive.api.Apigateway/ChangeVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Apigateway service

type ApigatewayServer interface {
	Login(context.Context, *creapptive_message.LoginRequest) (*creapptive_message.LoginReply, error)
	CreateUser(context.Context, *creapptive_message.CreateUserRequest) (*creapptive_message.CreateUserReply, error)
	GetUsers(context.Context, *creapptive_message.GetUsersRequest) (*creapptive_message.GetUsersReply, error)
	GetUserByID(context.Context, *creapptive_message.GetUserByIDRequest) (*creapptive_message.GetUserByIDReply, error)
	UpdateUser(context.Context, *creapptive_message.UpdateUserRequest) (*creapptive_message.UpdateUserReply, error)
	DeleteUser(context.Context, *creapptive_message.DeleteUserRequest) (*creapptive_message.DeleteUserReply, error)
	ChangePassword(context.Context, *creapptive_message.ChangePasswordRequest) (*creapptive_message.ChangePasswordReply, error)
	ResetPassword(context.Context, *creapptive_message.ResetPasswordRequest) (*creapptive_message.ResetPasswordReply, error)
	GetMyself(context.Context, *creapptive_message.GetMyselfRequest) (*creapptive_message.GetMyselfReply, error)
	CreatePrivilegeProfile(context.Context, *creapptive_message.CreatePrivilegeProfileRequest) (*creapptive_message.CreatePrivilegeProfileReply, error)
	GetPrivilegeProfiles(context.Context, *creapptive_message.GetPrivilegeProfilesRequest) (*creapptive_message.GetPrivilegeProfilesReply, error)
	GetPrivilegeProfileByID(context.Context, *creapptive_message.GetPrivilegeProfileByIDRequest) (*creapptive_message.GetPrivilegeProfileByIDReply, error)
	UpdatePrivilegeProfile(context.Context, *creapptive_message.UpdatePrivilegeProfileRequest) (*creapptive_message.UpdatePrivilegeProfileReply, error)
	DeletePrivilegeProfile(context.Context, *creapptive_message.DeletePrivilegeProfileRequest) (*creapptive_message.DeletePrivilegeProfileReply, error)
	GetLocationTree(context.Context, *creapptive_message.GetLocationTreeRequest) (*creapptive_message.GetLocationTreeReply, error)
	UpdateLocationTree(context.Context, *creapptive_message.UpdateLocationTreeRequest) (*creapptive_message.UpdateLocationTreeReply, error)
	GetScopeTree(context.Context, *creapptive_message.GetScopeTreeRequest) (*creapptive_message.GetScopeTreeReply, error)
	UpdateScopeTree(context.Context, *creapptive_message.UpdateScopeTreeRequest) (*creapptive_message.UpdateScopeTreeReply, error)
	ChangeVersion(context.Context, *creapptive_message.ChangeVersionRequest) (*creapptive_message.ChangeVersionReply, error)
}

func RegisterApigatewayServer(s *grpc.Server, srv ApigatewayServer) {
	s.RegisterService(&_Apigateway_serviceDesc, srv)
}

func _Apigateway_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).Login(ctx, req.(*creapptive_message.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).CreateUser(ctx, req.(*creapptive_message.CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetUsers(ctx, req.(*creapptive_message.GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetUserByID(ctx, req.(*creapptive_message.GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).UpdateUser(ctx, req.(*creapptive_message.UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).DeleteUser(ctx, req.(*creapptive_message.DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).ChangePassword(ctx, req.(*creapptive_message.ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).ResetPassword(ctx, req.(*creapptive_message.ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetMyself_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetMyselfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetMyself(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetMyself",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetMyself(ctx, req.(*creapptive_message.GetMyselfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_CreatePrivilegeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.CreatePrivilegeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).CreatePrivilegeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/CreatePrivilegeProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).CreatePrivilegeProfile(ctx, req.(*creapptive_message.CreatePrivilegeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetPrivilegeProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetPrivilegeProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetPrivilegeProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetPrivilegeProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetPrivilegeProfiles(ctx, req.(*creapptive_message.GetPrivilegeProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetPrivilegeProfileByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetPrivilegeProfileByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetPrivilegeProfileByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetPrivilegeProfileByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetPrivilegeProfileByID(ctx, req.(*creapptive_message.GetPrivilegeProfileByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_UpdatePrivilegeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.UpdatePrivilegeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).UpdatePrivilegeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/UpdatePrivilegeProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).UpdatePrivilegeProfile(ctx, req.(*creapptive_message.UpdatePrivilegeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_DeletePrivilegeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.DeletePrivilegeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).DeletePrivilegeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/DeletePrivilegeProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).DeletePrivilegeProfile(ctx, req.(*creapptive_message.DeletePrivilegeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetLocationTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetLocationTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetLocationTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetLocationTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetLocationTree(ctx, req.(*creapptive_message.GetLocationTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_UpdateLocationTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.UpdateLocationTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).UpdateLocationTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/UpdateLocationTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).UpdateLocationTree(ctx, req.(*creapptive_message.UpdateLocationTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_GetScopeTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.GetScopeTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).GetScopeTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/GetScopeTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).GetScopeTree(ctx, req.(*creapptive_message.GetScopeTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_UpdateScopeTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.UpdateScopeTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).UpdateScopeTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/UpdateScopeTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).UpdateScopeTree(ctx, req.(*creapptive_message.UpdateScopeTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apigateway_ChangeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(creapptive_message.ChangeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApigatewayServer).ChangeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/creapptive.api.Apigateway/ChangeVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApigatewayServer).ChangeVersion(ctx, req.(*creapptive_message.ChangeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apigateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "creapptive.api.Apigateway",
	HandlerType: (*ApigatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Apigateway_Login_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Apigateway_CreateUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Apigateway_GetUsers_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _Apigateway_GetUserByID_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Apigateway_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Apigateway_DeleteUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Apigateway_ChangePassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Apigateway_ResetPassword_Handler,
		},
		{
			MethodName: "GetMyself",
			Handler:    _Apigateway_GetMyself_Handler,
		},
		{
			MethodName: "CreatePrivilegeProfile",
			Handler:    _Apigateway_CreatePrivilegeProfile_Handler,
		},
		{
			MethodName: "GetPrivilegeProfiles",
			Handler:    _Apigateway_GetPrivilegeProfiles_Handler,
		},
		{
			MethodName: "GetPrivilegeProfileByID",
			Handler:    _Apigateway_GetPrivilegeProfileByID_Handler,
		},
		{
			MethodName: "UpdatePrivilegeProfile",
			Handler:    _Apigateway_UpdatePrivilegeProfile_Handler,
		},
		{
			MethodName: "DeletePrivilegeProfile",
			Handler:    _Apigateway_DeletePrivilegeProfile_Handler,
		},
		{
			MethodName: "GetLocationTree",
			Handler:    _Apigateway_GetLocationTree_Handler,
		},
		{
			MethodName: "UpdateLocationTree",
			Handler:    _Apigateway_UpdateLocationTree_Handler,
		},
		{
			MethodName: "GetScopeTree",
			Handler:    _Apigateway_GetScopeTree_Handler,
		},
		{
			MethodName: "UpdateScopeTree",
			Handler:    _Apigateway_UpdateScopeTree_Handler,
		},
		{
			MethodName: "ChangeVersion",
			Handler:    _Apigateway_ChangeVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apigateway.proto",
}

func init() { proto.RegisterFile("apigateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0x4f, 0x73, 0xe3, 0x34,
	0x18, 0x87, 0xc7, 0x2d, 0x2c, 0xac, 0xd8, 0xb6, 0xa9, 0x08, 0xed, 0x92, 0x6e, 0xc1, 0x78, 0x69,
	0x37, 0x04, 0x12, 0x77, 0x4b, 0x4f, 0xe5, 0x42, 0x77, 0x77, 0x26, 0xd3, 0x99, 0xed, 0xd0, 0x49,
	0x59, 0x0e, 0xdc, 0x84, 0xf3, 0xd6, 0xf1, 0x8e, 0x63, 0x09, 0x49, 0xae, 0x09, 0x33, 0x5c, 0x60,
	0x38, 0x70, 0xe3, 0xcf, 0x0d, 0xee, 0xf0, 0x81, 0xf8, 0x02, 0x1c, 0xf8, 0x20, 0x3b, 0x92, 0xe2,
	0xd8, 0x49, 0x6c, 0xc7, 0x3d, 0xb5, 0x93, 0xf7, 0x91, 0x7e, 0x8f, 0x25, 0xf9, 0x95, 0x51, 0x83,
	0xb0, 0xc0, 0x27, 0x12, 0x12, 0x32, 0xe9, 0x31, 0x4e, 0x25, 0xc5, 0x9b, 0x1e, 0x07, 0xc2, 0x98,
	0x0c, 0x6e, 0xa0, 0x47, 0x58, 0xd0, 0xda, 0x18, 0x83, 0x10, 0xc4, 0x07, 0x53, 0x6e, 0x3d, 0xf0,
	0x29, 0xf5, 0x43, 0x70, 0x09, 0x0b, 0x5c, 0x12, 0x45, 0x54, 0x12, 0x19, 0xd0, 0x48, 0x4c, 0xab,
	0x9f, 0xe8, 0x3f, 0x5e, 0xd7, 0x87, 0xa8, 0x2b, 0x12, 0xe2, 0xfb, 0xc0, 0x5d, 0xca, 0x34, 0xb1,
	0x4c, 0x3b, 0x07, 0x68, 0xfb, 0x6c, 0x16, 0x7f, 0x61, 0x62, 0x70, 0x03, 0xad, 0x0b, 0x32, 0xb9,
	0x6f, 0xd9, 0x56, 0xfb, 0xee, 0x40, 0xfd, 0x7b, 0xfc, 0x4b, 0x13, 0xa1, 0x8c, 0xc3, 0x23, 0xf4,
	0xfa, 0x73, 0xea, 0x07, 0x11, 0xb6, 0x7b, 0x39, 0xd5, 0xd4, 0x52, 0x97, 0x06, 0xf0, 0x6d, 0x0c,
	0x42, 0xb6, 0xde, 0xab, 0x20, 0x58, 0x38, 0x71, 0xf6, 0x7f, 0xfc, 0xf7, 0xff, 0x3f, 0xd6, 0x76,
	0x1d, 0x6c, 0x1e, 0xc7, 0xf3, 0x68, 0x1c, 0x49, 0x37, 0x54, 0xc0, 0xa9, 0xd5, 0xc1, 0x31, 0x42,
	0x4f, 0x39, 0x10, 0x09, 0x2f, 0x04, 0x70, 0x7c, 0x50, 0x34, 0x59, 0x56, 0x4f, 0x33, 0x1f, 0xae,
	0xc2, 0x54, 0xf0, 0x9e, 0x0e, 0x7e, 0xc7, 0x69, 0xe8, 0xe0, 0x58, 0x00, 0x77, 0x3d, 0x8d, 0xa8,
	0xd8, 0x97, 0xe8, 0xcd, 0x3e, 0x48, 0x05, 0x0b, 0x5c, 0x38, 0x5b, 0x5a, 0x4d, 0x23, 0x3f, 0xa8,
	0x86, 0x54, 0xe0, 0x8e, 0x0e, 0x6c, 0xe0, 0xcd, 0x2c, 0x30, 0x88, 0xae, 0x29, 0x16, 0xe8, 0xad,
	0x29, 0xf8, 0x64, 0x72, 0xfe, 0x0c, 0x1f, 0x56, 0xcc, 0xa4, 0x80, 0x34, 0xf1, 0xc3, 0x95, 0x5c,
	0x2e, 0xd4, 0x59, 0x0c, 0x8d, 0x11, 0x7a, 0xc1, 0x86, 0x95, 0xeb, 0x9a, 0xd5, 0x2b, 0xd7, 0x35,
	0x8f, 0x95, 0xac, 0x6b, 0xac, 0x91, 0xe9, 0x76, 0x3e, 0x83, 0x10, 0xaa, 0x62, 0xb3, 0x7a, 0x65,
	0x6c, 0x1e, 0x2b, 0x89, 0x1d, 0x6a, 0x44, 0xc5, 0xfe, 0x64, 0xa1, 0xcd, 0xa7, 0x23, 0x12, 0xf9,
	0x70, 0x49, 0x84, 0x48, 0x28, 0x1f, 0xe2, 0x8f, 0x0a, 0xcf, 0xc8, 0x1c, 0x93, 0xe6, 0x3f, 0xaa,
	0x83, 0x2e, 0x9f, 0x65, 0xed, 0xc0, 0xa6, 0x80, 0xb2, 0xf8, 0x01, 0x6d, 0x0c, 0x40, 0x80, 0x9c,
	0x39, 0xb4, 0x8b, 0x26, 0x9e, 0x43, 0x52, 0x85, 0xc3, 0x1a, 0xa4, 0x32, 0x68, 0x69, 0x83, 0xa6,
	0xb3, 0x95, 0x19, 0x70, 0x45, 0xa9, 0x78, 0x8a, 0xee, 0xf6, 0x41, 0x5e, 0x4c, 0x04, 0x84, 0xd7,
	0xb8, 0xec, 0xf4, 0x98, 0x72, 0x1a, 0xeb, 0xac, 0xa0, 0x54, 0xe4, 0x7d, 0x1d, 0x89, 0x71, 0x6e,
	0xe1, 0xc7, 0x26, 0xe3, 0x6f, 0x0b, 0xed, 0x98, 0xb7, 0xee, 0x92, 0x07, 0x37, 0x41, 0x08, 0x3e,
	0x5c, 0x72, 0x7a, 0x1d, 0x84, 0x80, 0x1f, 0x97, 0xbf, 0xa1, 0x8b, 0x6c, 0xea, 0xe2, 0xde, 0x66,
	0x88, 0x12, 0x6b, 0x6b, 0x31, 0xc7, 0xd9, 0xd7, 0x62, 0x2c, 0x65, 0xba, 0xcc, 0x40, 0xb9, 0xb7,
	0xfd, 0x2f, 0x0b, 0x35, 0xfb, 0x20, 0x17, 0xa7, 0x11, 0xd8, 0x2d, 0x79, 0xfe, 0x25, 0x32, 0x95,
	0xec, 0xd6, 0x1f, 0xa0, 0x14, 0x1f, 0x6a, 0xc5, 0x7d, 0xbc, 0x57, 0xa2, 0xa8, 0x5f, 0xd5, 0x7f,
	0x2c, 0xb4, 0x5b, 0x30, 0x85, 0x6e, 0x16, 0xc7, 0x35, 0xf3, 0xf2, 0x8d, 0xe3, 0xe8, 0x56, 0x63,
	0x94, 0xe6, 0xa1, 0xd6, 0xb4, 0x9d, 0x2a, 0x4d, 0xb5, 0x8e, 0x6a, 0xc3, 0x4d, 0x3b, 0xa8, 0xb7,
	0xe1, 0xc5, 0x6c, 0xe5, 0x86, 0x97, 0x0d, 0xa9, 0xb3, 0xe1, 0x59, 0x1b, 0x52, 0xa2, 0xa6, 0x81,
	0xd4, 0x13, 0x2d, 0x66, 0x2b, 0x45, 0xcb, 0x86, 0xd4, 0x11, 0x9d, 0x6b, 0x5c, 0x5b, 0x7d, 0x90,
	0xcf, 0xa9, 0xa7, 0x6f, 0xed, 0x2f, 0x39, 0x00, 0xee, 0x94, 0xec, 0x5f, 0x1e, 0x4a, 0xd5, 0xda,
	0xb5, 0xd8, 0x5c, 0xe7, 0xc0, 0xa6, 0x77, 0x85, 0xd3, 0xba, 0x39, 0x81, 0xbf, 0x59, 0x08, 0x9b,
	0x85, 0x9f, 0x13, 0xe9, 0x96, 0x6f, 0x50, 0x91, 0xcb, 0xc7, 0x75, 0x71, 0xa5, 0xf3, 0xbe, 0xd6,
	0x79, 0xd7, 0x69, 0xce, 0xeb, 0x64, 0x5b, 0x98, 0xa0, 0x7b, 0x7d, 0x90, 0x57, 0x1e, 0x65, 0xa0,
	0x65, 0x1e, 0x95, 0x3c, 0xe9, 0x8c, 0x48, 0x35, 0x0e, 0x56, 0x83, 0x4a, 0x60, 0x57, 0x0b, 0x6c,
	0x63, 0xd3, 0x49, 0x85, 0x2a, 0x9a, 0xc5, 0xf8, 0xd9, 0x42, 0x5b, 0xc6, 0x3a, 0x0b, 0xef, 0x94,
	0x3f, 0xda, 0x52, 0x7e, 0xbb, 0x16, 0xab, 0x14, 0x1e, 0x68, 0x85, 0x1d, 0x67, 0x3b, 0xa7, 0x90,
	0x5f, 0x80, 0x0d, 0x73, 0x07, 0x7d, 0x05, 0x5c, 0x04, 0x34, 0x2a, 0xbe, 0x4d, 0xe6, 0x90, 0xca,
	0xdb, 0x64, 0x81, 0x54, 0x02, 0x4d, 0x2d, 0xb0, 0xe9, 0xdc, 0xd3, 0x02, 0x37, 0xa6, 0xf4, 0xe4,
	0xd7, 0xb5, 0xdf, 0xcf, 0xfe, 0xb3, 0xf0, 0xf7, 0xc8, 0x39, 0xbf, 0xb8, 0xb2, 0xaf, 0xc0, 0x8b,
	0x79, 0x20, 0x27, 0xf6, 0x05, 0x89, 0x88, 0x0f, 0x63, 0x88, 0xa4, 0x7d, 0x35, 0x11, 0x12, 0xc6,
	0xf6, 0xd9, 0xe5, 0xb9, 0xf3, 0x05, 0xda, 0xcb, 0x65, 0x79, 0x74, 0xec, 0x06, 0x63, 0xd1, 0x15,
	0xd3, 0x41, 0x78, 0x6f, 0x24, 0x25, 0x13, 0xa7, 0xae, 0x9b, 0x24, 0x49, 0x6f, 0x01, 0x6c, 0xbd,
	0x3d, 0x84, 0x31, 0xfd, 0x7c, 0xfe, 0xd7, 0xe3, 0xf5, 0xc7, 0xbd, 0xa3, 0x8e, 0x65, 0x1d, 0x37,
	0x08, 0x63, 0x61, 0x30, 0x3d, 0x16, 0x2f, 0x05, 0x8d, 0x4e, 0x97, 0x7e, 0x19, 0x7c, 0x86, 0xd6,
	0x4f, 0x8e, 0x4e, 0xf0, 0x09, 0xea, 0x0c, 0x40, 0xc6, 0x3c, 0x82, 0xa1, 0x9d, 0x8c, 0x20, 0xb2,
	0xe5, 0x08, 0x6c, 0x0e, 0x82, 0xc6, 0xdc, 0x03, 0x7b, 0x48, 0x41, 0xd8, 0x11, 0x95, 0x36, 0x7c,
	0x17, 0x08, 0xd9, 0xc3, 0x77, 0xd0, 0x6b, 0x7f, 0xae, 0x59, 0x6f, 0x7c, 0xdd, 0xa9, 0xf0, 0x36,
	0xdf, 0xaa, 0xb3, 0xef, 0xe1, 0x6f, 0xee, 0xe8, 0x8f, 0xe9, 0x4f, 0x5f, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x3d, 0x92, 0x78, 0xf4, 0xcb, 0x0b, 0x00, 0x00,
}
