# IMS Security Management System user service config file
---
# individual service settings
service:
    authen:
        endpoint: "/api"                        # service base endpoint (note: must begin with '/')
        database:
            dbname: "imsSecurityAuthenDB"       # database name
            host: "127.0.0.1"                   # database host address
            port: 27017                         # database port number
            user: ""                            # database user name (note: NEVER save user name here, should pass it through environment variable)
            password: ""                        # database password (note: NEVER save password here, should pass it through environment variable)
        default_password: "Initial9999Password" # user's default initial password; used upon new user with empty password or user password reset
        more_less_cost: 0                       # more (+ve number) or less (-ve number) encryption cost relative to the default value (min: 4, default: 10, max: 31) (e.g. set this to 2 will have cost value 12) (note: the higher the cost, the longer to hash and compare password; e.g. setting 0 takes 90~110ms, 1 takes 180~220ms)

# global settings
setting:
    database:
        retry_count: 20                         # database retry connecting database count
        retry_interval: 3                       # database retry connecting database base interval in second; interval time = 1-based retry index * interval
        migration_path: "deploy/migrations"     # define the database migration directory path name
        migration_table: "schema_migrations"    # migration table name (note: migrate's default collection name is "schema_migrations", better follow it)

# log settings
log:
    console: true                               # enable/disable log output to console
    file: ""                                    # log output file
    level: "info"                               # log levels: debug, info, error

